# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modStr', models.IntegerField(default=0)),
                ('modDex', models.IntegerField(default=0)),
                ('modCon', models.IntegerField(default=0)),
                ('modInt', models.IntegerField(default=0)),
                ('modWis', models.IntegerField(default=0)),
                ('modCha', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StatBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField(default=10)),
                ('dexterity', models.IntegerField(default=10)),
                ('constitution', models.IntegerField(default=10)),
                ('intelligence', models.IntegerField(default=10)),
                ('wisdom', models.IntegerField(default=10)),
                ('charisma', models.IntegerField(default=10)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='charClass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='Characters_app.Class'),
        ),
        migrations.AddField(
            model_name='character',
            name='stats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='Characters_app.StatBlock'),
        ),
    ]
