# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='...description...'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
